services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    api:
        build:
            context: ./ # Relative path to Dockerfile
            dockerfile: Dockerfile # Name of the Dockerfile
        image: docker.io/renu277/simpleblog_renu.v1
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
            - PORT=3000
        ports:
            - "8085:3000"