services:
#Postgress Database
    postgres:
        image: docker.io/postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
    #Redis Database
    redis:
        image: docker.io/redis
        command: ["redis-server", "--protected-mode", "no"]
        #Express API Server
    api:
        build:
            context: ./server
        image: docker.io/renu277/complex-api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
      #React Client
    client:
        build:
            context: ./client
        image: docker.io/renu277/complex-client
      #Worker Service
    worker:
        build:
            context: ./worker
        image: docker.io/renu277/complex-worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
      #Nginx Controller
    nginx:
        depends_on:
            - api
            - client
        restart : always
        build: 
            context: ./nginx
        ports:
            - "8082:80"

